##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=ptmalloc3 record-support replay-support dummy-support

include $(LEVEL)/Makefile.common
