##===- projects/sample/lib/sample/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=tsxleaprecord

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common


CFLAGS=-march=native -mrtm -I../
CPPFLAGS=-march=native -mrtm -I../
CXXFLAGS=-march=native -mrtm -I../

