##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=dyckgraph wrapper transformer dyckaa trace-support leap-support canary-support

include $(LEVEL)/Makefile.common
