Import('env')

DIRS = ["Annotation", "DyckGraph", "DyckCG", "Transformer", "DyckAA", "TraceSupport", "LeapSupport"] #, "canary-support"

SCONSCRIPTS = []
for DIR in DIRS:
    SCRIPT = DIR + "/SConscript"
    SCONSCRIPTS.append(SCRIPT)

SConscript(SCONSCRIPTS, exports='env')
