#!/bin/bash

APP=pbzip2
LIBPATH=.

while getopts "c:dl:L:" arg #":" means the previous option needs arguments
do
        case $arg in
             c)
		COMPILE=$OPTARG
                ;;
	     d)
		DEBUG="-d"
                ;;
	     l)
		LIB=$OPTARG
		;;
	     L)
		LIBPATH=$OPTARG
		;;
             ?)  #unknown args
		exit -1
                ;;
        esac
done

if [ -n "$COMPILE" ];then
        canary -$COMPILE $APP.bc -o $APP.t.bc
fi

if [ -n "$LIB" ];then
	# how to link
	if [ -f $APP.t.bc ]; then
		echo "clang++ $APP.t.bc -o $APP -lpthread -lbz2 -l$LIB -L$LIBPATH"
		clang++ $APP.t.bc -o $APP.exe -lpthread -lbz2 -l$LIB -L$LIBPATH
	else
		echo "clang++ $APP.bc -o $APP -lpthread -lbz2 -l$LIB -L$LIBPATH"
		clang++ $APP.bc -o $APP.exe -lpthread -lbz2 -l$LIB -L$LIBPATH
	fi
fi

if [ -n "$DEBUG" ];then
        tar -cf test.tar ../../

	./pbzip2.exe -k -f -p3 test.tar

        if [ -f "test.tar" ]; then
            rm test.tar
        fi

        if [ -f "test.tar.bz2" ]; then
	    rm test.tar.bz2
        fi
fi
